version: '3'

services:
  generic-qc:
    build: .
    image: pwlb/generic-qc:0.2.0

    environment:
      - JOBS=10

    volumes:
      # fastq should contain sub-directories corresponding to runs
      - ./test/fastq:/input:ro
      - ./test/output:/output:rw
