version: '3'

services:
  generic-qc:
    image: jsschrepping/generic-qc:jss_v0.0.2
    command: --jobs 11

    volumes:
      # fastq should contain sub-directories corresponding to runs
      - ./test/fastq:/input:ro
      - ./test/output:/output:rw
