version: '3'

services:
  generic-qc:
    build: .
    image: jsschrepping/generic-qc:latest
    command: --jobs 11

    volumes:
      # fastq should contain sub-directories corresponding to runs
      - ./test/fastq:/input:ro
      - ./test/output:/output:rw
